language: python
python:
  - "3.9"

addons:
  chrome: stable

# safelist (indicate the only branches to check)
branches:
  only:
    - master

install:
  - pip install -r requirements.txt

before_script:
  - wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE
  - wget https://chromedriver.storage.googleapis.com/`cat LATEST_RELEASE`/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.9.5/bin
env:
  global:
    - DJANGO_SETTINGS_MODULE="djangoProject.settings.travis"

services:
  - postgresql

script:
  - python manage.py test